### ISSUE TITLE
Activity detection not working properly

### ISSUE THREAD

**Issue by sh4wn** [codito/gnome-pomodoro#218]
Hello,

Somewhere in the 3.18 release (and still present in the current 3.20 release), the activity detection stopped working. When a break is finished, it immediately starts the next pomodoro, even when I'm away from keyboard.

It could be that some input devices are sending signals although I'm not using them, but I'm not sure. My setup:

- Microsoft Sculpt Ergonomic keyboard
- Wacom Intuos Small Pen tablet 

Anything I can do to help you debug this issue?

**Comment by kamilprusko** [comment]
Hi,

Apparently, support for tablets in Clutter (GNOME Shell is based on it) landed around 3.18
https://mail.gnome.org/archives/commits-list/2015-October/msg05705.html

I've made a patch 8666ec59ce934cb3c7f75045cfa7567c29671962.

It would be helpful if you could try it, because I don't have a tablet. To install use [gnome-3.20](https://github.com/codito/gnome-pomodoro/tree/gnome-3.20) branch, instructions are on our site http://gnomepomodoro.org/.

**Comment by sh4wn** [comment]
Thanks for working on it! I'll watch this for further progress.

**Comment by kamilprusko** [comment]
I was wrong - support for tablets hasn't been merged in Clutter yet... It might be a driver issue. Are you using Wayland or X11?

In your spare time please run attached script, it will produce "clutter-events.log". Run it and do nothing for a while, in terminal you should start seeing the culprit events.

[clutter-events.tar.gz](https://github.com/codito/gnome-pomodoro/files/241489/clutter-events.tar.gz)

Thanks

**Comment by sh4wn** [comment]
I've attached the logfile. There are only a few events logged, and those events occurred when I actually moved the mouse (with my pen tablet).

I'm running X11 by the way.

[clutter-events.txt](https://github.com/codito/gnome-pomodoro/files/242071/clutter-events.txt)

**Comment by kamilprusko** [comment]
Thanks. It doesn't look a software issue...

I assume it's a similar issue as with innacurate/jumpy optical mouse. Best solution would be to make a custom idle/activity detection in Pomodoro, more tolerant about "motion" events.

It will require some code refactoring. I hope to get back to this before GNOME 3.22.

**Comment by coalwater** [comment]
Hi,
I have this same issue, not sure when it started happening, I'm using wayland, the timer starts even when the screen is off ( due to inactivity ), I really liked the activity detection feature, now I need to reset the timer whenever I come back from a break.

If there's any thing I could provide you, I'm willing to help.

**Comment by kamilprusko** [comment]
@coalwater, I see that it's broken in master branch. Will fix this.

**Comment by kamilprusko** [comment]
Fixed in a1ce242dc6029229de46339cbb9d08d894752de6.

What happened for me was ```AudioRaiseVolume``` key being emitted and not flagged as "synthetic". Idle monitor treats it as an user event. Would happen when notification sounds are enabled and no music is playing.

Packages with new version and fix are available from http://gnomepomodoro.org and [openSUSE Build Service](http://software.opensuse.org/download.html?project=home:kamilprusko&package=gnome-pomodoro), not yet from distro repos.

Please reopen it if you keep having issues.

**Comment by sh4wn** [comment]
Ok, so with the 0.12 release the activity detection is still not working properly, and I noticed this is a regression from the 0.11 which works fine. 

Another (possibly unrelated) bug: when it's time for a break, two timer overlays open. I have to press escape twice to close both screens, and there's a sort of shadow effect due to the fact that the break overlay is a bit transparent and the font size of the top overlay is a little bit smaller. It's hard to make a screenshot of that because pressing a button closes one overlay.

Any ideas what could cause this?

**Comment by sh4wn** [comment]
I think the commit for this issue has also fixed the problem described above: https://github.com/codito/gnome-pomodoro/issues/218

Thanks a lot for your work, it now works completely as expected again!

**Comment by kamilprusko** [comment]
Thanks @sh4wn for confirming
