### ISSUE TITLE
Pomodoro is showing two icons on panel

### ISSUE THREAD

**Issue by belenos** [codito/gnome-pomodoro#256]
I'm using Gnome 3.22.2 on Fedora 25. It happens (not all the time) after rebooting the system and if I click on "quit", the first one remains. Did I messed up with something or is it a bug?

![screenshot from 2016-12-17 07-47-58](https://cloud.githubusercontent.com/assets/1954831/21286254/956ed0ba-c42d-11e6-9927-4d0cbc669153.png)

**Comment by kamilprusko** [comment]
Looks like a bug. I too use Fedora 25 and didn't see it with code from master branch.

Pomodoro seems to think you're not running GNOME or that the extension failed to start...

1. What's your version of Pomodoro ```$ gnome-pomodoro --version```

2. Does ```$ echo $XDG_CURRENT_DESKTOP``` returns "GNOME" ?

3. Can you run gnome-pomodoro in the terminal?

    $ gnome-pomodoro --quit
    $ G_MESSAGES_DEBUG=all gnome-pomodoro

**Comment by belenos** [comment]
1. Pomodoro 0.12.3
2. Yes!
3. It returns this:
(gnome-pomodoro:16707): Gtk-DEBUG: Connecting to session manager
** (gnome-pomodoro:16707): DEBUG: capability.vala:52: Enable capability gnome-shell.notifications
** (gnome-pomodoro:16707): DEBUG: capability.vala:52: Enable capability gnome-shell.indicator
** (gnome-pomodoro:16707): DEBUG: capability.vala:52: Enable capability gnome-shell.accelerator
** (gnome-pomodoro:16707): DEBUG: capability.vala:52: Enable capability gnome-shell.reminders
** (gnome-pomodoro:16707): DEBUG: capability.vala:52: Enable capability gnome-shell.hide-system-notifications
** (gnome-pomodoro:16707): DEBUG: capability.vala:52: Enable capability gnome.idle-monitor
** (gnome-pomodoro:16707): DEBUG: gnome-shell-extension.vala:261: Extension state = enabled

**Comment by 183amir** [comment]
@belenos you have enabled both the appindicator (used in Unity the one that has a white menu in your screenshot) and the shell extension (used in Gnome shell). I don't have the appindicator of pomodoro installed and its not showing up there for me.
I don't know how to get rid of the appindicator which is the one you should disable but for now you can disable the extension from here: https://extensions.gnome.org/local/

**Comment by kamilprusko** [comment]
Fixed by dbb2250c468a360f565b4ff1d4fdc7797bab7c4b.

Sorry @belenos for late reply. It should omit appindicator on GNOME completely now. Though I have seen that appindicator sometimes does not get destroyed properly, that's another issue...

**Comment by RichAyotte** [comment]
I'm still seeing this issue in version 0.13
![screenshot from 2017-01-26 08-03-38](https://cloud.githubusercontent.com/assets/294987/22332284/1b161cca-e39e-11e6-9502-a3800456e9d9.png)

**Comment by kamilprusko** [comment]
@RichAyotte : Thanks for reporting, I'll try reproduce it.

**Comment by kamilprusko** [comment]
Fixed in d548e69d72c6675932898de142918ebb38c6d978 and adce9b0da94b9b5f315fa6a4b9bec650fbe2bb37.

**Comment by miguelfito** [comment]
Hi all!

I'm on Fedora 25 with gnome-pomodoro 0.13.1 version and still facing the same issue:

![captura de pantalla de 2017-05-01 01-59-40](https://cloud.githubusercontent.com/assets/879123/25569176/0ba72c02-2e12-11e7-8945-ca9a44725a41.png)

**Comment by kamilprusko** [comment]
@miguelfito I'll look into it.

For now, to put it right you may Quit the Pomodoro and open it again...

**Comment by miguelfito** [comment]
@kamilprusko, I think the problem appears when you're using GNOME Classic session, so maybe it isn't a bug indeed... 

It would be a good idea to manage showing or not appindicator in system tray if you're using GNOME Classic session in Pomodoro's Preferences, or maybe handle it in a similar way if you have the GNOME extension activated or not. 

At this moment, I'm using Fedora 25 with GNOME in Wayland and it's working really fine (**v0.13.1**):

![image](https://cloud.githubusercontent.com/assets/879123/25579187/cc998d3e-2e75-11e7-8e95-fd0c56b6c700.png)

Thank you so much for this amazing software! ;)

**Comment by dcervenkov** [comment]
Seems this is still an issue on Ubuntu 17.10 (`echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME`) with the newest version 0.13.4. Is there a way to get the GNOME shell extension working without the second tray icon?

BTW, the two icons are **always** spawned for me as opposed to what @belenos reported a year ago. Interacting with the non-shell icon often (but not always) crashes the whole shell.

@kamilprusko, could we get some info about this - an ETA on the fix or even a wontfix?

**Comment by kamilprusko** [comment]
@dcervenkov It's fixed in master branch / upcoming 0.14.0 release. Changes can't be easily backported so I'll omit this in point releases.

**Comment by dcervenkov** [comment]
@kamilprusko, great, thanks for the info.

**Comment by thinkhuman** [comment]
Definitely not fixed. I'm running Ubuntu 17.10 (Gnome default), and I've tried the gamut of uninstall/reinstall/toggle/restart. `echo $XDG_CURRENT_DESKTOP` returns `ubuntu:GNOME`.

**Comment by AbdElraoufSabri** [comment]
## Workaround 1: Remove extension
Just delete the extension from /usr/share/gnome-shell/extensions/
`rm -f /usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/`

## {OR} Workaround 2: Remove indicator
```shell
sudo mv plugins/indicator.plugin plugins/indicator.plugin.bak
# stop pomodoro
killall gnome-pomodoro -s KILL
# Re-enable extension
gnome-shell-extension-tool -e pomodoro@arun.codito.in
```

**Comment by Apol0x** [comment]
Hi everyone!
Any one knows how to deal with the same problem on **gnome-pomodoro v0.13.4** on **Ubuntu 18.04** ?
Thanks :sweat_smile:

**Comment by sedmo** [comment]
Wow guys thank you @AbdElraoufSabri  for the extension solve. I was able to get to the extensions but couldn't see it in there even with ```ls -a``` command @Apol0x  did you try the reccomendation above? I will stick to the official one i.e. not on the extensions page on Gnome. I feel the one from ubuntu software is good because 1) you can easily uninstall and 2) it works well with caffeine since it easily shows up as an application you can whitelist

**Comment by sedmo** [comment]
@Apol0x  if you downloaded it from the ubuntu software store, which currently has version 0.13.4 all you would need to do is simply unintall it from there . The issue is that maybe you alse downloaded it from extensions.gnome like I did and you now have it showing twice in which case if you follow the first reccomendation of @AbdElraoufSabri  it would solve it for you

**Comment by Apol0x** [comment]
Thanks a lot @sedmo  for the recomendation. I think that's exactly was happend to me. Finally I resolved it with the second option of @AbdElraoufSabri . Thanks folks !;)

**Comment by thinkhuman** [comment]
@AbdElraoufSabri 'sSecond option worked perfectly for me. Thanks to all for the problem solving!

**Comment by tamvcspk** [comment]
@AbdElraoufSabri second option worked for me on Ubuntu 18.04

**Comment by TharinduRajarathna** [comment]
> ```shell
> gnome-shell-extension-tool -e pomodoro@arun.codito.in
> ```

Thanks a lot, @AbdElraoufSabri  for sharing those steps & I also like the second option. Is there a proper way to restart the app without using the gnome-shell-extension-tool -e pomodoro@arun.codito.in command (and re-enabling the extension in tweaks tool). Assume if I quit the Pomodoro app & I want to run it again. In that case, is there a way to change the command associated with the icon which is in the apps section (or in the gnome dock).

**Comment by tstrijdhorst** [comment]
Second option fixed the dual icons for me, but I still have that if there is a break I see 2 timers stacked on each other with some transparency. Before the fix I thought this was happening because it was running twice but now that it still happens I'm not so sure.

Anyone else experiencing this issue?

**Comment by boliwiz** [comment]
Workaround 2: Remove indicator worked for me too. 
Pomodoro 0.13.4 on Ubuntu 18.04.

**Comment by sekanitembo** [comment]
I had installed through both Ubuntu Software Center and [https://extensions.gnome.org](https://extensions.gnome.org). I had already applied workaround two from above. I removed pomodoro through USC, which just left the plugins dir. I did a: `sudo rm -rf /usr/lib/x86_64-linux/gnu/gnome-pomodoro/` and now only have the one instance (and I think no kruft left behind?).

**Comment by sekanitembo** [comment]
I'm also getting that @tstrijdhorst.
