### ISSUE TITLE
Resuming Broken After Break

### ISSUE THREAD

**Issue by liamtimms** [codito/gnome-pomodoro#466]
This is strange issue but the sequence to reproduce it is as follows:
1. gnome-pomodoro starts a break and come up with the pomodoro lock screen
2. GNOME responds to a lack of activity by locking the screen
3. The GNOME lock screen is removed as normal by entering a password
4. a 2nd lockscreen immediately following the first appears beneath GNOME Shell and blocks access to any open windows,

This situation has the following attributes:
1. GNOME Shell (the bar at the top and the dock) can be interacted with as normal (e.g. the system can be shutdown through the GUI)
2. no open program is visible or accessible (browsers cannot be closed, work cannot be saved, etc.)
3. no program takes any input (cannot save a screenshot)
4. this 2nd lock screen can be interacted with (and a password entered) but does not respond to the entering of the password and remains regardless of action
5. exiting, restarting or otherwise killing gnome-pomodoro has no effect 
6. this never happens if gnome-pomodoro is paused or set to "pomodoro" rather than "short/long break"
7. this never happens if I remain active at the machine during the break and do not allow GNOME to lock the screen

This is occurring on an Xorg session of GNOME 3.36 and gnome-pomodoro 0.17.0 . I am using nvidia drivers on the affected machine and so cannot easily test on a Wayland session.

**Comment by dimsuz** [comment]
I have similar behaviour with the only difference being that I don't have access to gnome shell interfaces at all:

* long break starts
* after 5m gdm locks screen
* long break ends
* I tap any key to unlock screen
* All I see is the cursor and a black screen, impossible to interact, keys don't work, no way to disable it

All apps continue to run.

GNOME 3.36, x11, nvidia, gnome-pomodoro 0.17.0

**Comment by liamtimms** [comment]
@dimsuz seems to have gotten worse. I just encountered the "cursor and black screen" you describe on booting GNOME. This was fixed by uninstalling the extension.

**Comment by ktpx** [comment]
Same issue here ...stuff runs, but cannot log back in after screensaver takes over.  I see my desktop briefly, then it just goes back to the login page.  Have to restart gdm etc to get back in.

**Comment by liamtimms** [comment]
@ktpx What you describe where "[you] see my desktop briefly, then it just goes back to the login page" was also true sometimes in my case.

**Comment by chrisjbillington** [comment]
Experiencing this too in Arch. Dual monitors, intel graphics.

Installed the extension from the AUR, worked until a long break, then gnome locked the screen. Don't remember if I unlocked or if it was already like this upon the screen turning on again, but dash to panel was visible and I could click on stuff on it. But no windows could be raised and the login interface was there instead of the desktop - I could type my password into it, but it would remain. I rebooted. Then black screen with only the cursor visible upon logging in. Had to uninstall the extension from a tty.

**Comment by liamtimms** [comment]
@chrisjbillington that was the exact same sequence I experienced and the same solution too. I've since reinstalled the extension but disabled the "screen notification" option. Since doing so I haven't had it take down the whole session again.

**Comment by chrisjbillington** [comment]
@liamtimms I'm having difficulty doing that.

The extension does not even appear in gnome-tweaks or the gnome extensions tool until I restart gnome-shell (this is unusual! Other extensions appear there right away), at which point gnome-shell does not start, as the extension is already enabled at restart-time leading to the black-screen issue. Disabling the extension via the command line interface `gnome-extensions` doesn't help, and disabling the 'screen notification' in dconf after installing the extension but before restarting gnome-shell or rebooting does not seem to help either.

**Comment by real-or-random** [comment]
> @chrisjbillington I've since reinstalled the extension but disabled the "screen notification" option. Since doing so I haven't had it take down the whole session again.

I can confirm that this is the best work around for now. 

But this should be fixed, it's a very annoying issue. People can lose their unsaved work in the worst case.

**Comment by chrisjbillington** [comment]
Fixed by this perhaps?

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2446

This fix is in gnome-shell 3.36.2, so I'll re-enable the "screen notification" setting and see if it still breaks.

**Comment by letorbi** [comment]
I've just tried the screen notification with gnome-shell 3.36.2 and the problem still exists :(

Just an idea: The [Drop Down terminal extension for GMOME](https://github.com/zzrough/gs-extensions-drop-down-terminal) also creates a fullscreen-overlay that does not block the lock screen. Maybe it's helpful to look into how they've implemented it....

**Comment by sojusnik** [comment]
Same "black screen with mouse cursor" issue here on Ubuntu 20.04. The only temporary solution is to turn of the "screen notification" until this issue is patched.

**Comment by Ih0rko** [comment]
> Fixed by this perhaps?
> 
> https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2446
> 
> This fix is in gnome-shell 3.36.2, so I'll re-enable the "screen notification" setting and see if it still breaks.

Looks like issue is really fixed in gnome-shell 3.36.2.

**Comment by sojusnik** [comment]
> > Fixed by this perhaps?
> > https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2446
> > This fix is in gnome-shell 3.36.2, so I'll re-enable the "screen notification" setting and see if it still breaks.
> 
> Looks like issue is really fixed in gnome-shell 3.36.2.

The previous comment says the opposite:

> I've just tried the screen notification with gnome-shell 3.36.2 and the problem still exists :(
> 
> Just an idea: The [Drop Down terminal extension for GMOME](https://github.com/zzrough/gs-extensions-drop-down-terminal) also creates a fullscreen-overlay that does not block the lock screen. Maybe it's helpful to look into how they've implemented it....

**Comment by Ih0rko** [comment]
Issue is really still present. Finally captured fresh logs:
[log.txt](https://github.com/codito/gnome-pomodoro/files/4671595/log.txt)
`Object .Gjs_pomodoro_arun_codito_in_notifications_PomodoroSource (0x55d2449bf160), has been already deallocated — impossible to emit any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs`

I'm not sure if it could help but looks like it's reproduced if trying to unlock screen in several seconds after break finished(race condition?). I was not experiencing issue for almost a week if unlock screen in a minute after break finished.
